# Generated by Django 4.1 on 2022-09-04 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='startup',
            name='logo',
        ),
    ]
