# Generated by Django 4.1 on 2022-09-04 18:18

from django.db import migrations
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('organizer', '0002_remove_startup_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newslink',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, max_length=63, populate_from=['title'], unique=True),
        ),
        migrations.AlterField(
            model_name='startup',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, help_text='A label for URL config.', max_length=31, populate_from=['name'], unique=True),
        ),
    ]
